<?php

namespace Terminalbd\KpiBundle\Repository;

use App\Entity\Admin\Terminal;
use Gedmo\Tree\Entity\Repository\MaterializedPathRepository;
use  Terminalbd\KpiBundle\Entity\MarkChart;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarkChartRepository extends MaterializedPathRepository
{



    public function build_child($oldID,$array)
    {

        $em = $this->_em;
        global $exclude;
        //echo $menu_id;
        $tempTree="";

        $childData = $this->findBy(array('parent'=>$oldID),array('name'=>'asc'));

        foreach ( $childData as $child ){

            if ( $child->getId() != $child->getParent()->getId() )
            {
                if(in_array($child->getId(), $array)){
                    $tempTree .= '<option value="'.$child->getId().'" rel="'.$this->depth.'">';
                    for ( $c=0;$c<$this->depth;$c++ )
                    { $tempTree .= "&nbsp;&nbsp;&nbsp;"; }
                    for ( $c=0; $c < $this->depth; $c++ )
                    { $tempTree .= ">"; }
                    $tempTree .= "" . $child->getName(). "</option>";
                }

                $this->depth++;
                $tempTree .=$this->build_child($child->getId(),$array);
                $this->depth--;
                if(is_array($exclude)){
                    array_push($exclude,$child->getId());
                }
            }
        }

        return $tempTree;
    }

    public function getRootCategoriesQB() {

        $qb = $this->createQueryBuilder('c');

        return $qb
            ->where('c.status = :status')
            ->andWhere($qb->expr()->isNull('c.parent'))
            ->setParameter('status', 1)
            ->orderBy('c.name', 'ASC');
    }

    public function getRootCategories() {
        return $this->getRootCategoriesQB()->getQuery()->getResult();
    }

    public function getFeaturedRootCategories() {
        $qb = $this->getRootCategoriesQB();

        return $qb
            ->andWhere($qb->expr()->eq('c.feature', true))
            ->getQuery()
            ->getResult();
    }


    public function getFlatTree()
    {

        $categories = $this->childrenHierarchy();

        $this->buildFlatTree($categories, $array);

        return $array;
    }

    public function getFlatExpenseCategoryTree($globalOption)
    {

        $categories = $this->createQueryBuilder("node")
            ->where('node.terminal = :terminal')->setParameter('terminal', 1)
            ->andWhere('node.level = :level')->setParameter('level', 1)
            ->orderBy('node.level','ASC')
            ->getQuery()->getResult();

        $arr =array();
        $array =array();
        if(!empty($categories)){
            /* @var $category MarkChart */
            foreach($categories as $category){
                $arr[] = array(
                    'id' => $category->getId(),
                    'name' => $category->getName(),
                    'level' => $category->getLevel(),
                    '__children' => $this->childrenHierarchy($category)
                );
            }
            $this->buildFlatCategoryTree($arr , $array);
        }
        return $array == null ? array() : $array;
    }

    private function buildFlatCategoryTree($categories, &$array = array())
    {
        usort($categories, function($a, $b){
            return strcmp($a["name"], $b["name"]);
        });

        foreach($categories as $category) {
            $array[] = $this->find($category['id']);
            if(isset($category['__children'])) {
                $this->buildFlatCategoryTree($category['__children'], $array);
            }
        }
    }

    private function buildFlatTree($categories, &$array = array())
    {
        usort($categories, function($a, $b){
            return strcmp($a["name"], $b["name"]);
        });

        foreach($categories as $ExpenseCategory) {
            $array[$ExpenseCategory['id']] = $this->formatLabel($ExpenseCategory['level'], $ExpenseCategory['name']);
            if(isset($ExpenseCategory['__children'])) {
                $this->buildFlatTree($ExpenseCategory['__children'], $array);
            }
        }
    }

    private function buildFlatExpenseCategoryTree($categories, &$array = array())
    {
        usort($categories, function($a, $b){
            return strcmp($a["name"], $b["name"]);
        });

        foreach($categories as $ExpenseCategory) {
            $array[] = $this->find($ExpenseCategory['id']);
            if(isset($ExpenseCategory['__children'])) {
                $this->buildFlatExpenseCategoryTree($ExpenseCategory['__children'], $array);
            }
        }
    }

    private function formatLabel($level, $value) {

        $level = $level - 1;
        return str_repeat("-", $level * 3) . str_repeat(">", $level) . "$value";

    }

    public function getCategoryOptions($globalOption){

        $ret = array();
        $em = $this->_em;
        $categories = $this->findBy(array('globalOption' => $globalOption ,'status' => 1),array('name'=>'asc'));

        foreach( $categories as $cat ){

            if( !$cat->getParent() ){
                continue;
            }
            $key = $cat->getParent()->getName();
            if(!array_key_exists($key, $ret) ){
                $ret[ $cat->getParent()->getName() ] = array();
            }
            $ret[ $cat->getParent()->getName() ][ $cat->getId() ] = $cat;
        }

        return $ret;

        //\Doctrine\Common\Util\Debug::dump($ret);
        //exit;
    }


    public function getChildRecords($parent)
    {

        $qb = $this->createQueryBuilder('e');
        $qb->join('e.parent','p');
        $qb->where('p.slug = :slug')->setParameter('slug',$parent);
        $result = $qb->getQuery()->getResult();
        return $result;
    }

    public function getAttributes()
    {
        $qb = $this->createQueryBuilder('e');
        $qb->select('e.name AS attributesName', 'e.mark AS attributesMark');
        $qb->where('settingGroup.slug = :settingGroupSlug')->setParameter('settingGroupSlug', 'attributes');
//        $qb->where('parent.slug = :slug')->setParameter('slug', 'product-wise-sales-achievement');
        $qb->orderBy('e.name','ASC');
        $qb->leftJoin('e.settingGroup','settingGroup');

        $results = $qb->getQuery()->getArrayResult();
        return $results;
    }


    public function getMarkDistribution($breedType)
    {
        $qb = $this->createQueryBuilder('e');
        $qb->select('e.name AS markDistribution');
        $qb->where('parentParent.slug = :parentParentslug')->setParameter('parentParentslug','product-wise-sales-achievement');
        $qb->andWhere('parent.name = :breedType')->setParameter('breedType',$breedType);

        $qb->leftJoin('e.parent','parent');
        $qb->leftJoin('parent.parent','parentParent');

        $results = $qb->getQuery()->getArrayResult();
        $data = [];
        foreach ($results as $result){
            $data[] = $result;
        }
        return $results;

    }

    public function salesProductItems()
    {
        $em = $this->_em;
        $qb = $this->createQueryBuilder('e');
        $qb->join('e.parent','p');
        $qb->where('p.slug = :slug')->setParameter('slug','sales');
        $qb->andWhere('e.salesMode = :mode')->setParameter('mode','feed');
        $result = $qb->getQuery()->getResult();
        return $result;
    }

    public function findProduct($name)
    {
        $em = $this->_em;
        $qb = $this->createQueryBuilder('e');
        $qb->where('e.name = :name')->setParameter('name',$name);
        $qb->andWhere('e.salesMode = :mode')->setParameter('mode','feed');
        $result = $qb->getQuery()->getResult();
        return $result;
    }

    public function findUserMarkAttribute($reportMode, $chart)
    {
        $em = $this->_em;
        $qb = $this->createQueryBuilder('e');
        $qb->join('e.reportMode','m');
        $qb->where('e.id = :id')->setParameter('id',$chart);
        $qb->andWhere('m.id =:mode')->setParameter('mode',$reportMode);
        $result = $qb->getQuery()->getOneOrNullResult();
        return $result;
    }

    public function groupReportMode($reportMode)
    {
        $qb = $this->createQueryBuilder('e');
        $qb->join('e.reportMode','m');
        $qb->join('e.settingGroup', 's');
        $qb->join('e.parent','p');
        $qb->join('p.parent','gp');
        $qb->where('m.slug =:mode')->setParameter('mode',$reportMode);
        $qb->andWhere("s.slug = 'attributes'");
//        $qb->orderBy('gp.name','ASC');
        $qb->orderBy('gp.ordering','ASC');
        $qb->addOrderBy('p.ordering','ASC');
        $qb->addOrderBy('e.ordering','ASC');
        $result = $qb->getQuery()->getResult();
        return $result;
    }


    public function getAttributesForSummary()
    {
        $qb = $this->createQueryBuilder('e');
        $qb->select('e.name AS attributesName', 'e.slug');
        $qb->where("e.slug IN (:slugArr)")->setParameter('slugArr',['doc-sales-vs-collection','outstanding-limit-actual-feed','individual-team-members-achievement','regional-achievement','district-achievement','minimum-50-c-category-agents-converts-to-b','minimum-50-d-category-agents-converts-to-c']);

        $results = $qb->getQuery()->getArrayResult();
        return $results;
    }



}
